packages:
  - "packages/*"

# Reduce the risk of installing newly compromised packages before detection.
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@contena/*"
  - "@typescript/native-preview"
  - "happy-dom"

overrides:
  "@colordx/core": 5.5.0
  baseline-browser-mapping: 2.11.15
  "crossws@0.4.12": 0.4.10
  electron-to-chromium: 1.5.411
  esbuild: ^0.28.1
  vite: ^8.0.16

shamefullyHoist: true
autoInstallPeers: true
strictPeerDependencies: false
preferWorkspacePackages: true
enablePrePostScripts: true
preferFrozenLockfile: true
preferOffline: true
verifyDepsBeforeRun: false
linkWorkspacePackages: deep
allowBuilds:
  esbuild: true
  oxfmt: true
  oxlint: true
